package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculadoraQuskiResponseSimulation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CalculadoraQuskiResultSimulation")
	private com.relative.brecreditosnuevos.objetosnegocio.CalculadoraQuskiResultSimulation calculadoraQuskiResultSimulation;

	public CalculadoraQuskiResponseSimulation() {
	}

	public com.relative.brecreditosnuevos.objetosnegocio.CalculadoraQuskiResultSimulation getCalculadoraQuskiResultSimulation() {
		return this.calculadoraQuskiResultSimulation;
	}

	public void setCalculadoraQuskiResultSimulation(
			com.relative.brecreditosnuevos.objetosnegocio.CalculadoraQuskiResultSimulation calculadoraQuskiResultSimulation) {
		this.calculadoraQuskiResultSimulation = calculadoraQuskiResultSimulation;
	}

	public CalculadoraQuskiResponseSimulation(
			com.relative.brecreditosnuevos.objetosnegocio.CalculadoraQuskiResultSimulation calculadoraQuskiResultSimulation) {
		this.calculadoraQuskiResultSimulation = calculadoraQuskiResultSimulation;
	}

}