package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculadoraQuskiResultGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "SimularResponseGarantias")
	private com.relative.brecreditosnuevos.objetosnegocio.SimularResponseGarantias simularResponseGarantias;

	public CalculadoraQuskiResultGarantias() {
	}

	public com.relative.brecreditosnuevos.objetosnegocio.SimularResponseGarantias getSimularResponseGarantias() {
		return this.simularResponseGarantias;
	}

	public void setSimularResponseGarantias(
			com.relative.brecreditosnuevos.objetosnegocio.SimularResponseGarantias simularResponseGarantias) {
		this.simularResponseGarantias = simularResponseGarantias;
	}

	public CalculadoraQuskiResultGarantias(
			com.relative.brecreditosnuevos.objetosnegocio.SimularResponseGarantias simularResponseGarantias) {
		this.simularResponseGarantias = simularResponseGarantias;
	}

}