package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesInternasSalida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Variable")
	private java.util.List<com.relative.brecreditosnuevos.objetosnegocio.Variable> variable;

	public VariablesInternasSalida() {
	}

	public java.util.List<com.relative.brecreditosnuevos.objetosnegocio.Variable> getVariable() {
		return this.variable;
	}

	public void setVariable(
			java.util.List<com.relative.brecreditosnuevos.objetosnegocio.Variable> variable) {
		this.variable = variable;
	}

	public VariablesInternasSalida(
			java.util.List<com.relative.brecreditosnuevos.objetosnegocio.Variable> variable) {
		this.variable = variable;
	}

}