package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlOpcionesRenovacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("OpcionesRenovacion")
	private com.relative.brecreditosnuevos.objetosnegocio.OpcionesRenovacion opcionesRenovacion;

	public XmlOpcionesRenovacion() {
	}

	public com.relative.brecreditosnuevos.objetosnegocio.OpcionesRenovacion getOpcionesRenovacion() {
		return this.opcionesRenovacion;
	}

	public void setOpcionesRenovacion(
			com.relative.brecreditosnuevos.objetosnegocio.OpcionesRenovacion opcionesRenovacion) {
		this.opcionesRenovacion = opcionesRenovacion;
	}

	public XmlOpcionesRenovacion(
			com.relative.brecreditosnuevos.objetosnegocio.OpcionesRenovacion opcionesRenovacion) {
		this.opcionesRenovacion = opcionesRenovacion;
	}

}