package com.relative.brecreditosnuevos.objetosnegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlVariablesInternasSalida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("VariablesInternas")
	private com.relative.brecreditosnuevos.objetosnegocio.VariablesInternasSalida variablesInternas;

	public XmlVariablesInternasSalida() {
	}

	public com.relative.brecreditosnuevos.objetosnegocio.VariablesInternasSalida getVariablesInternas() {
		return this.variablesInternas;
	}

	public void setVariablesInternas(
			com.relative.brecreditosnuevos.objetosnegocio.VariablesInternasSalida variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

	public XmlVariablesInternasSalida(
			com.relative.brecreditosnuevos.objetosnegocio.VariablesInternasSalida variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

}